--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Steellgold/MoreKits
build-by-default: true
branches:
  - main
projects:
  MoreKits:
    path: ""
    icon: MoreKits.png
    libs:
      - src: CortexPE/Commando/Commando
        version: ^2.0.0
      - src: jojoe77777/FormAPI/libFormAPI
        version: ^1.3.0
...